### ISSUE TITLE
[Bug] ZenTabs conflict

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#111]
### 1. Summary

Issues not send for me, if I use [**ZenTabs**](https://packagecontrol.io/packages/Zen%20Tabs) package.

### 2. Expected behavior

Successfully sending my issues.

### 3. Actual behavior

![ZenTabs conflict](http://i.imgur.com/VaepVtz.gif)

```python
command: new_github_issue {}
GitHub Issue >>> folder path E:\Mega.co.nz\MEGAsync Загрузки\Джинджерины\ТТД is not a git repo
GitHub Issue >>> folder path E:\Киролайна is not a git repo
GitHub Issue >>> folder path E:\Mega.co.nz\MEGAsync Загрузки\Джинджерины\Грейс Ло is not a git repo
GitHub Issue >>> folder path E:\Sublime Text 3\Data\Packages\User is not a git repo
GitHub Issue >>> folder path E:\About Sasha Chernykh is not a git repo
GitHub Issue >>> find username wbond and repo_name package_control_channel
GitHub Issue >>> folder path E:\Mega.co.nz\MEGAsync Загрузки\Джинджерины\ТТД\Кубок Вызова 2 is not a git repo
GitHub Issue >>> find username Kristinita and repo_name SashaSublime
GitHub Issue >>> folder path E:\AutoHotkey is not a git repo
GitHub Issue >>> folder path E:\Sublime Text 3\Data\Packages\Plugins is not a git repo
GitHub Issue >>> folder path E:\Test is not a git repo
GitHub Issue >>> find username Kristinita and repo_name Kristinita
GitHub Issue >>> find username Kristinita and repo_name SashaChocolatey
GitHub Issue >>> find username Kristinita and repo_name KristinitaTest
chr evt: d (0x64)
chr evt: i (0x69)
chr evt: v (0x76)
chr evt: i (0x69)
chr evt: n (0x6e)
chr evt: i (0x69)
chr evt: t (0x74)
chr evt: e (0x65)
chr evt: s (0x73)
key evt: keypad_divide
chr evt: / (0x2f)
chr evt: g (0x67)
chr evt: i (0x69)
chr evt: s (0x73)
chr evt: s (0x73)
chr evt: u (0x75)
chr evt: e (0x65)
chr evt: s (0x73)
GitHub Issue >>> username is divinites
GitHub Issue >>> repo name is gissues
GitHub Issue >>> The first 8 digits of your GitHub Token is ddb40937
GitHub Issue >>> Your own username is Kristinita
GitHub Issue >>> Create new view to write the issue
GitHub Issue >>> insert a blank issue
GitHub Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/issues
08:16:33 INFO  requests.packages.urllib3.connectionpool:805            _new_conn() Starting new HTTPS connection (1): api.github.com
key evt: control+`
command: show_panel {"panel": "console", "toggle": true}
08:16:35 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repos/divinites/gissues/issues?state=all HTTP/1.1" 200 None
GitHub Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/labels
08:16:35 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repos/divinites/gissues/labels HTTP/1.1" 200 None
08:16:35 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/issues?state=all&page=2 HTTP/1.1" 200 None
08:16:35 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/issues?state=all&page=3 HTTP/1.1" 200 None
08:16:35 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/issues?state=all&page=4 HTTP/1.1" 200 None
GitHub Issue >>> the joint url is https://api.github.com/repos/divinites/gissues/commits
08:16:36 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repos/divinites/gissues/commits HTTP/1.1" 200 None
08:16:36 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/commits?page=2 HTTP/1.1" 200 None
08:16:36 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/commits?page=3 HTTP/1.1" 200 None
08:16:36 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/commits?page=4 HTTP/1.1" 200 None
08:16:36 DEBUG requests.packages.urllib3.connectionpool:401        _make_request() "GET /repositories/61034356/commits?page=5 HTTP/1.1" 200 None
GitHub Issue >>> finish acquiring label, commit and issue title
command: drag_select {"event": {"button": 1, "x": 380.5, "y": 89.5}}
GitHub Issue >>> current cursor is located at 37
GitHub Issue >>> find the row 1 and the col 18
command: word_highlight_click {"event": {"button": 1, "x": 380.5, "y": 89.5}}
GitHub Issue >>> current cursor is located at 37
GitHub Issue >>> find the row 1 and the col 18
command: drag_select {"event": {"button": 1, "x": 364.5, "y": 71.5}}
GitHub Issue >>> current cursor is located at 18
GitHub Issue >>> find the row 0 and the col 18
command: word_highlight_click {"event": {"button": 1, "x": 364.5, "y": 71.5}}
GitHub Issue >>> current cursor is located at 18
GitHub Issue >>> find the row 0 and the col 18
chr evt: T (0x54)
GitHub Issue >>> current cursor is located at 19
GitHub Issue >>> find the row 0 and the col 19
GitHub Issue >>> the trigger is  
chr evt: e (0x65)
GitHub Issue >>> current cursor is located at 20
GitHub Issue >>> find the row 0 and the col 20
chr evt: s (0x73)
GitHub Issue >>> current cursor is located at 21
GitHub Issue >>> find the row 0 and the col 21
GitHub Issue >>> the trigger is  
chr evt: t (0x74)
GitHub Issue >>> current cursor is located at 22
GitHub Issue >>> find the row 0 and the col 22
GitHub Issue >>> the trigger is  
command: drag_select {"event": {"button": 1, "x": 359.5, "y": 226.5}}
GitHub Issue >>> current cursor is located at 221
GitHub Issue >>> find the row 5 and the col 0
command: word_highlight_click {"event": {"button": 1, "x": 359.5, "y": 226.5}}
GitHub Issue >>> current cursor is located at 221
GitHub Issue >>> find the row 5 and the col 0
chr evt: E (0x45)
GitHub Issue >>> current cursor is located at 222
GitHub Issue >>> find the row 5 and the col 1
GitHub Issue >>> the trigger is 

chr evt: x (0x78)
GitHub Issue >>> current cursor is located at 223
GitHub Issue >>> find the row 5 and the col 2
GitHub Issue >>> the trigger is 

chr evt: a (0x61)
GitHub Issue >>> current cursor is located at 224
GitHub Issue >>> find the row 5 and the col 3
GitHub Issue >>> the trigger is 

chr evt: m (0x6d)
GitHub Issue >>> current cursor is located at 225
GitHub Issue >>> find the row 5 and the col 4
GitHub Issue >>> the trigger is 

chr evt: p (0x70)
GitHub Issue >>> current cursor is located at 226
GitHub Issue >>> find the row 5 and the col 5
GitHub Issue >>> the trigger is 

chr evt: l (0x6c)
GitHub Issue >>> current cursor is located at 227
GitHub Issue >>> find the row 5 and the col 6
GitHub Issue >>> the trigger is 

chr evt: e (0x65)
GitHub Issue >>> current cursor is located at 228
GitHub Issue >>> find the row 5 and the col 7
GitHub Issue >>> the trigger is 

key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
chr evt: g (0x67)
chr evt: i (0x69)
chr evt: p (0x70)
chr evt: u (0x75)
command: post_or_update_issue {}
GitHub Issue >>> post or update?
GitHub Issue >>> post
GitHub Issue >>> try to find the view in repo_dictionary...
Traceback (most recent call last):
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 77, in find_repo_info
  File "libgit.utils in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 72, in show_stock
KeyError: 35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 134, in run
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 81, in find_repo_info
Exception: Which repository should I post?
```

### 4. Settings

My `User\ZenTabs.sublime-settings` file:

```json
{
    "open_tab_limit": 7,
    "show_full_path": true
}

```

My `User\github_issue.sublime-settings` file:

```json
{
    "commit_completion_trigger": "$",
    "custom_completion_scope":
    [
        "text.html.markdown.gfm"
    ],
    "debug": 1,
    "syntax": "Packages/MarkdownEditing/Markdown.tmLanguage",
    "token": "ddb4093794cc719f0my_correct taken",
    "username": "Kristinita",
    "wrap_width": 0
}

```

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install and set ZenTabs → I restart Sublime Text → if number of my tabs more than 7, last used tabs was closed for me. I open many tabs → I create issue as in GIF → some tabs was closed for me → I post issue as in GIF → I get stack trace, issue not posted for me.

### 6. Feature request

Example of expected behavior: I get error in console `Exception: Which repository should I post?` → quick panel will open for me → I print or paste `user/repository` again → issue successfully send for me.

### 7. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
Actually. Actual behacior very incomfortable.

Thanks.

**Comment by Kristinita** [comment]
I get actual behavior very often.

**Comment by divinites** [comment]
Thanks, I will look into it soon.

**Comment by Kristinita** [comment]
@divinites , what you think about `open_in_new_window` option? Users will write new issue in a new window.

Thanks.

**Comment by divinites** [comment]
Hi, @Kristinita, sorry for late reply. I reviewed this issue and I did not think the feature request could be justified. I believe the correct way to do it is the current way, that is, the program throws an exception when it cannot find the repo and stop the whole procedure. Then, if you choose manually entre the repo name, it will start from the very beginning again.

In this way, all obselete data will be erased from the memory, everything stays calm. However, if I do not raise an exception, instead, I let you to entre repo name manually, there is a danger that some previous information will still exist in the global variables.

If something is wrong, let it crash! I believe the philosophy of erlang :)

**Comment by Kristinita** [comment]
@divinites, I need to write issue in a new window. But if <kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → if I want to create issue for my sidebar repository, I need write `Kristinita/Repository` manually each time. It may spend a time.

Thanks.

**Comment by divinites** [comment]
So, what you really want is to create issue in a new window?

**Comment by Kristinita** [comment]
> So, what you really want is to create issue in a new window?

I already write AutoHotkey script for it:

```autohotkey
Sleep, 1000
Send, {LControl Down}
Sleep, 1000
Send, {LShift Down}
Sleep, 1000
Send, {p}
Sleep, 1000
Send, {LShift Up}
Sleep, 1000
Send, {LControl Up}
Sleep, 1000
Send, New Window
Sleep, 1000
Send, {Enter}
Sleep, 1000
Send, {LControl Down}
Sleep, 1000
Send, {LShift Down}
Sleep, 1000
Send, {p}
Sleep, 1000
Send, {LShift Up}
Sleep, 1000
Send, {LControl Up}
Sleep, 1000
Send, GitHub Issue: Create Issue
Sleep, 1000
Send, {Enter}
Sleep, 1000
Send, {Enter}
Sleep, 1000
Send, {LControl Down}
Sleep, 1000
Send, {v}
Sleep, 1000
Send, {LControl Up}
Sleep, 1000
Send, {Enter}
#esc::ExitApp
```

Thanks.

**Comment by divinites** [comment]
Thanks!  So I will try to solve your another request first then.

**Comment by Kristinita** [comment]
But it would be nice, if users, that use ZenTabs, don't need write issue in a new window.

Thanks.
