### ISSUE TITLE
[BUG] can't update issues

### ISSUE THREAD

**Issue by xiang578** [divinites/gissues#120]
I can use cmd+S to update issues. when i open debug mod, i see this log in console, how can i fix this bug ?
```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/xiangrunye/Library/Application Support/Sublime Text 3/Installed Packages/GitHubIssue.sublime-package/libgit/issue.py", line 349, in run
    original_issue['issue']['title']))
TypeError: 'NoneType' object is not subscriptable
```

sublime version 3.1.1 build 3176

when i reinstall this package, i even couldn't open issues
```
GitHub Issue >>> I am showing the issue list!
GitHub Issue >>> username is xiang578
GitHub Issue >>> repo name is xiang578.github.io
Traceback (most recent call last):
  File "/Users/xiangrunye/Library/Application Support/Sublime Text 3/Installed Packages/GitHubIssue.sublime-package/github_issue.py", line 209, in on_enter_repo_info
  File "/Users/xiangrunye/Library/Application Support/Sublime Text 3/Installed Packages/GitHubIssue.sublime-package/libgit/issue.py", line 21, in __init__
  File "/Users/xiangrunye/Library/Application Support/Sublime Text 3/Installed Packages/GitHubIssue.sublime-package/libgit/issue.py", line 62, in __init__
  File "/Users/xiangrunye/Library/Application Support/Sublime Text 3/Installed Packages/GitHubIssue.sublime-package/libgit/github.py", line 12, in __init__
AttributeError: 'module' object has no attribute 'Session'
```

**Comment by xiang578** [comment]
I solve this problem by reinstall sublime text
