### ISSUE TITLE
encoding bugs

### ISSUE THREAD

**Issue by divinites** [divinites/gissues#57]
### Remaining errors:
1. I still not can get debugging information.  
   
   ```
   No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'  
   ```
2. When I update this issue:  

``` python
command: update_github_issue {}
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
  File "./python3.3/encodings/cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 1561: character maps to <undefined>
Logged from file GitHubIssue.sublime-package, line 203
```

**Comment by divinites** [comment]
cp1251 is for Russian language, it is an encoding problem,  @Kristinita have you encountered this kind of problem before?

**Comment by Kristinita** [comment]
@divinites, yes, I have this problem, for example, for [Terminality](https://github.com/spywhere/Terminality) plugin:

![Terminality encoding](http://i.imgur.com/OIX5dDT.gif)

I have Russian Windows localization and I have setting `"fallback_encoding": "Cyrillic (Windows 1251)"`. 

Thanks.

**Comment by divinites** [comment]
OKay, I now have time to look at the encoding issue. FIrst thing first, I will need to add somg logger information so that we can see which piece of code is problematic. I will push a new version soon.

**Comment by divinites** [comment]
@Kristinita  If you still cannot get debug information, I am not quite clear why but in the mean time you have a workaround, you can type this in sublime console:

``` python
import logging
logging.basicConfig(level=logging.INFO)
```

Then you can see all debug information.

**Comment by Kristinita** [comment]
``` python
import logging
logging.basicConfig(level=logging.INFO)
```

I'm sorry, but this not helped for me. But I can get logging information to my Sublime Text without plugins and user settings.

### Steps to reproduce

I add in issue #60 comment:

``` markdown
### Request

Add by default the possibility to select for creating new issue syntax that the user typically uses for Markdown documents.

### Justification

1. In `MarkdownEditing — Markdown GFM` syntax I have many snippets, completions, macros and syntax highlight for computer languages when I use only in Markdown GFM syntax. When I do not use snippets, completions, macros and syntax highlight for computer languages I spend a lot of time.
2. Since GitHub Issues use Markdown markup, I see no point in creating an additional syntax, if we have syntaxes for Markdown.

### Extended behavior

`GitHub Issue: Create Issue` → I select user/repository → GitHub Issue file always was opened in `MarkdownEditing — Markdown GFM` syntax (or other syntax, which users use for Markdown documents), not `GitHub Issue — Markdown` syntax. 

### Not helped

I can not always use for issues crating MarkdownEditing — Markdown GFM syntax because file, when I wrote issue, not have extension. I can not add my preferable Markdown syntax for create issue file:

1. `View` → `Syntax` → `Open all with current extension as...` → `MarkdownEditing` → `Markdown GFM`.
2. [ApplySyntax](https://github.com/facelessuser/ApplySyntax) plugin.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126


Thanks.
```

`GitHub Issues: Update Issue` → I get in console:

``` python
INFO:GitHubIssue:found the view in repo_dictionary
INFO:GitHubIssue:take out original issue
INFO:GitHubIssue:curcial line is {'end': 41, 'comment_end': [], 'add_comment': 7, 'header_end': 39, 'comment_start': []}
Exception in thread Thread-7:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "libgit.issue in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 227, in run
  File "libgit.utils in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 227, in get_issue_post
  File "libgit.utils in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 181, in generate_issue_header
AttributeError: 'NoneType' object has no attribute 'group'
```

Thanks.

**Comment by Kristinita** [comment]
@divinites , I find conflicted plugin. Please, install [1Self](https://github.com/1self/sublime-text-plugin) → restart Sublime Text → create issue use GitHub Issues → you must no get logging information.

(I have 100+ plugins. In the process of debugging I disable plug-ins, starting with the most recent alphabetically — Zeal. I disable the plugins in the reverse alphabetical order. But the problem was in the first alphabetically plugin. If I was starting of disable plugins in alphabetical order, I would immediately find the cause. I am loser 😭.)

Thanks.

**Comment by divinites** [comment]
@Kristinita, I have had a look at the source code of 1self. I now understand why there is a conflict. In `1self.py`, I found this:

``` python
logging.basicConfig(filename=LOG_FILENAME,level=logging.DEBUG,format='%(asctime)s %(levelname)s:%(message)s')

```

So the level of logging is fixed to DEBUG anyway and the log was redirected to LOG_FILENAME instead of console.

**Comment by divinites** [comment]
For this problem:

``` python
INFO:GitHubIssue:found the view in repo_dictionary
INFO:GitHubIssue:take out original issue
INFO:GitHubIssue:curcial line is {'end': 41, 'comment_end': [], 'add_comment': 7, 'header_end': 39, 'comment_start': []}
Exception in thread Thread-7:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "libgit.issue in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 227, in run
  File "libgit.utils in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 227, in get_issue_post
  File "libgit.utils in E:\Sublime Text Build 3126 For Debug\Data\Installed Packages\GitHubIssue.sublime-package", line 181, in generate_issue_header
AttributeError: 'NoneType' object has no attribute 'group'
```

It is because the header is unrecognized. the issue header must be like this

``` markdown
# Title         : 
## Number       : 
## State        : 
## Label        : 
## Locked       : 
## Assignee     : 
```

If there is an additional space, the regular expression matches will fail and an exception will be raised.
