### ISSUE TITLE
[Bug] repo URL Error!

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#74]
### Summary

I can not create issue in 2.5.0 version.
### Expected behavior

Successful create and post issue.
### Actual behavior

`Грейс Ло`, `Киролайна`, `www` and so on — folders in my side bar.

``` python
command: new_github_issue {}
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло', 'config', '--get', 'remote.origin.url']
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\Киролайна', 'config', '--get', 'remote.origin.url']
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\wamp\\www', 'config', '--get', 'remote.origin.url']
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\Sublime Text 3\\Data\\Packages\\User', 'config', '--get', 'remote.origin.url']
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\SashaSublime', 'config', '--get', 'remote.origin.url']
['C:\\Program Files\\Git\\bin\\git.exe', '-C', 'E:\\About Sasha Chernykh', 'config', '--get', 'remote.origin.url']
Traceback (most recent call last):
  File "libgit.github in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 64, in get_github_repo_info
Exception: repo URL error!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 97, in run
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 139, in format_entries
  File "libgit.github in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 69, in get_github_repo_info
Exception: Error in find repo URL!
```
### Steps to reproduce

<kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → I get stack trace. I restart Sublime Text → I get still stack trace.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126
## Thanks.

---
### UPD

Now sometimes I get other error in console:

`No git :( list index out of range`

**Comment by divinites** [comment]
I cannot reproduce it in either Windows or Mac OS. But I added some debug information and  pushed a new version 2.5.3. If it happened again, we will know better about the reasons. In the meantime, I suggest that you delete your custom configuration of **git_path** and let the system automatically find the git executables.

**Comment by Kristinita** [comment]
@divinites , I remove my configuration of **git_path** → I restart Sublime Text → now if I want create new issue, I get stack trace:

``` python
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
command: new_github_issue {}
Traceback (most recent call last):
  File "libgit.github in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 63, in get_github_repo_info
Exception: repo URL error!， the url is Kristinita.rainyday.js


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 123, in run
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 165, in format_entries
  File "libgit.github in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 68, in get_github_repo_info
Exception: Error in find repo URL!
```

Thanks.

**Comment by divinites** [comment]
That's a very important clue, what is Kristinita.rainyday.js then? this is what the git command dig out from the folder, is it your repo_name?

**Comment by Kristinita** [comment]
### Actual behavior

I have `rainyday.js`script in my repository → I [remove](https://github.com/Kristinita/Kristinita.github.io/commit/7730883fd9ee598710ebbdcfb7d06ed2b577134a) `rainyday.js` → I get behavior:

![Without rainyday.js](http://i.imgur.com/uPdgSNU.gif)

I still get error in console:

```
No git :( [Errno 2] No such file or directory: 'E:\\Mega.co.nz\\MEGAsync Загрузки\\Джинджерины\\Грейс Ло\\.git\\HEAD'
```

### Feature request

May be you added option `"disable_local_repositories": true`? I do not use my local repositories for GitHub Issues, but I have many bugs.

Thanks.

**Comment by divinites** [comment]
@Kristinita  as you wish, the new version add option`"disable_local_repositories": false`, you can override it in your custom settings.

**Comment by divinites** [comment]
@Kristinita v2.5.5 should solve this problem for you.
