### ISSUE TITLE
[Bug] Issues not posted after one unsuccessful issue post

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#96]
### Summary

I can not post not posted issues after restart Sublime Text. If I post one issue wrong, I can not post other issues. I need restart Sublime Text, then post other issues. In #88, #89, #90 and #91 issues I try reproduce this problem.

### Expected behavior

1. Opportunity post not posted issues after restart Sublime Text.
2. Opportunity post new issues, if previous posted are wrong.

### Actual behavior

1. I can not post not posted issues after restart Sublime Text.
2. I can not post new issues, if previous posted are wrong.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

<kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → `divinites/gissues` → I wrote first issue → I no posted issue and I close Sublime Text.

I restart Sublime Text → in first issue tab I press <kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: post/update issue` → I get stack trace:

```python
command: post_or_update_issue {}
GitHub Issue >>> post or update?
GitHub Issue >>> post
GitHub Issue >>> try to find the view in repo_dictionary...
Traceback (most recent call last):
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 77, in find_repo_info
  File "libgit.utils in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 71, in show_stock
KeyError: 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 134, in run
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 81, in find_repo_info
Exception: Which repository should I post?
```

I no restart Sublime Text → <kbd>Ctrl+Shift+P</kbd> → `GitHub Issues: Create Issue` → `divinites/gissues` → I wrote second issue → `GitHub Issues: post/update issue` → I get stack trace:

```python
command: post_or_update_issue {}
GitHub Issue >>> post or update?
GitHub Issue >>> post
GitHub Issue >>> try to find the view in repo_dictionary...
GitHub Issue >>> repo_info_storage contains None
Traceback (most recent call last):
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 79, in find_repo_info
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "github_issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 134, in run
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 81, in find_repo_info
Exception: Which repository should I post?
```

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by divinites** [comment]
- The first bug is not actually a bug, it is an expected behaviour. Since repo information is not supposed to be preserved after a restart of Sublime Text. It could only be fixed if I create and manage some cache files, but I doubted whether it is worthwhile to jeopardize the `User` directory with that.
- The second one seems to be a real bug, but I cannot replicate it.

**Comment by divinites** [comment]
close at this moment.
